### ISSUE TITLE
"lv" feature doesn't work for NetworkFeatures

### ISSUE THREAD

**Issue by maciek-git** [simetenn/uncertainpy#15]
AttributeError: ("'NetworkFeatures' object has no attribute 'lv'", 'Error in calculation of feature: lv')

with the following constructor: 
features=un.NetworkFeatures(features_to_run=["mean_firing_rate", "mean_isi", "cv", "mean_cv", "fanofactor", "lv", "mean_lv", "binned_isi", "corrcoef", "covariance"])

same thing happens for the mean_lv feature

**Comment by simetenn** [comment]
The documentation for network features was unfortunately not updated when those two features where renamed some time ago. The correct name is "local_variation" and "mean_local_variation". The documentation have been updated to reflect this in commit 113cf051185e028297e3bd25a9ab6c5e61e91ed3.
