### ISSUE TITLE
load pandas dataframe or csv

### ISSUE THREAD

**Issue by fab6** [simetenn/uncertainpy#27]
Hi,
do you have an advice how to load a pandas dataframe or a csv file?

data = un.Data()
data.load("filename")
variance = data["nr_spikes"].variance

I actually would like to use uncertainpy mainly for post-processing.
Thank you!

**Comment by simetenn** [comment]
Hi,

At the moment there is, unfortunately, no good method for loading a pandas dataframe or a CSV file.
It is possible to manually add model evaluations to a `Data` object, but there is no support for performing calculations from existing data.

What type of postprocessing would you like to do? The reason I ask is that Uncertainpy needs to run the model for specific sets of model parameters, which depends on the used method as well as the problem. As such, Uncertainpy is probably not well suited for post-processing.

**Comment by fab6** [comment]
Hi, ok, I think I see my misunderstanding now.
Thank you!
