### ISSUE TITLE
error: fit_regression() got an unexpected keyword argument 'rule'

### ISSUE THREAD

**Issue by BeichuanH** [simetenn/uncertainpy#43]
Hi,

After the installation in python (using anaconda in Ubuntu), the running for the "coffee_cup" or other example cases shows the same error: fit_regression() got an unexpected keyword argument 'rule'.

I don't know if it is because of wrong installation or other reasons. Thanks for your help.

**Comment by simetenn** [comment]
Hi! This should be fixed in version 1.2.2 :)
